// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserManagement.APIGateway.Data;

#nullable disable

namespace UserManagement.APIGateway.Migrations
{
    [DbContext(typeof(UserManagementDbContext))]
    [Migration("20250705052514_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserManagement.APIGateway.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Otp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44e59eb2-dcf3-4824-9b91-9e82c7a757d4"),
                            Address = "DDA",
                            City = "Dikhan",
                            Contact = "03429765706",
                            Country = "Pakistan",
                            Email = "asad@gmail.com",
                            FirstName = "Asad",
                            Image = "image",
                            LastName = "Khan",
                            Otp = "123",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = 0,
                            UserName = "asad_1"
                        },
                        new
                        {
                            Id = new Guid("937f789f-5bdf-43d0-8e62-912743264f85"),
                            Address = "Tank Ada",
                            City = "Dikhan",
                            Contact = "03457788900",
                            Country = "Pakistan",
                            Email = "ali@gmail.com",
                            FirstName = "Ali",
                            Image = "image",
                            LastName = "Khan",
                            Otp = "009",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = 1,
                            UserName = "ali_2"
                        },
                        new
                        {
                            Id = new Guid("73bcf899-bee3-4f95-8f7d-bbdaa1aa53ff"),
                            Address = "Haji Abad",
                            City = "FaisalAbad",
                            Contact = "03334566430",
                            Country = "Pakistan",
                            Email = "faizan@gmail.com",
                            FirstName = "Faizan",
                            Image = "image",
                            LastName = "Ahmed",
                            Otp = "111",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = 0,
                            UserName = "fazan_0"
                        },
                        new
                        {
                            Id = new Guid("c7601d97-7cf8-4057-a53f-6500209e6083"),
                            Address = "Korangi",
                            City = "Karachi",
                            Contact = "03001002001",
                            Country = "Pakistan",
                            Email = "alya@gmail.com",
                            FirstName = "Alya",
                            Image = "image",
                            LastName = "Khan",
                            Otp = "333",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0],
                            Role = 1,
                            UserName = "alya_9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
